# Downloading Market and Fundamental Data with `yfinance`

## Imports & Settings

In [216]:
import warnings
warnings.filterwarnings('ignore')

In [217]:
import pandas as pd
import yfinance as yf

## How to work with a Ticker object

In [218]:
symbol = 'MCD'
ticker = yf.Ticker(symbol)

### Show ticker info

In [219]:
pd.Series(ticker.info).head(20)

address1                                        110 North Carpenter Street
city                                                               Chicago
state                                                                   IL
zip                                                                  60607
country                                                      United States
phone                                                         630 623 3000
website                                    https://corporate.mcdonalds.com
industry                                                       Restaurants
industryDisp                                                   Restaurants
sector                                                   Consumer Cyclical
sectorDisp                                               Consumer Cyclical
longBusinessSummary      McDonald's Corporation operates and franchises...
fullTimeEmployees                                                   100000
companyOfficers          [{'maxAge': 1, 'name': 'Mr. Christopher J. Kem...
auditRisk                                                                6
boardRisk                                                                3
compensationRisk                                                         3
shareHolderRightsRisk                                                    7
overallRisk                                                              4
governanceEpochDate                                             1690848000
dtype: object

### Get market data

In [220]:
data = ticker.history(period='730d',
                      interval='60m',
                      start=None,
                      end=None,
                      actions=True,
                      auto_adjust=True,
                      back_adjust=False)
data.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 5090 entries, 2020-10-01 09:30:00-04:00 to 2023-08-25 15:30:00-04:00
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Open          5090 non-null   float64
 1   High          5090 non-null   float64
 2   Low           5090 non-null   float64
 3   Close         5090 non-null   float64
 4   Volume        5090 non-null   int64
 5   Dividends     5090 non-null   float64
 6   Stock Splits  5090 non-null   float64
dtypes: float64(6), int64(1)
memory usage: 318.1 KB

### View company actions

In [221]:
# show actions (dividends, splits)
ticker.actions

                           Dividends  Stock Splits
Datetime
2020-11-30 09:30:00-05:00       1.29           0.0
2021-02-26 09:30:00-05:00       1.29           0.0
2021-05-28 09:30:00-04:00       1.29           0.0
2021-08-31 09:30:00-04:00       1.29           0.0
2021-11-30 09:30:00-05:00       1.38           0.0
2022-02-28 09:30:00-05:00       1.38           0.0
2022-06-03 09:30:00-04:00       1.38           0.0
2022-08-31 09:30:00-04:00       1.38           0.0
2022-11-30 09:30:00-05:00       1.52           0.0
2023-02-28 09:30:00-05:00       1.52           0.0
2023-06-02 09:30:00-04:00       1.52           0.0

In [222]:
ticker.dividends

Datetime
2020-11-30 09:30:00-05:00    1.29
2021-02-26 09:30:00-05:00    1.29
2021-05-28 09:30:00-04:00    1.29
2021-08-31 09:30:00-04:00    1.29
2021-11-30 09:30:00-05:00    1.38
2022-02-28 09:30:00-05:00    1.38
2022-06-03 09:30:00-04:00    1.38
2022-08-31 09:30:00-04:00    1.38
2022-11-30 09:30:00-05:00    1.52
2023-02-28 09:30:00-05:00    1.52
2023-06-02 09:30:00-04:00    1.52
Name: Dividends, dtype: float64

In [223]:
ticker.splits

Series([], Name: Stock Splits, dtype: float64)

### Annual and Quarterly Financial Statement Summary

In [224]:
ticker.financials

,2023-03-31,2022-12-31,2022-09-30,2022-06-30,2022-03-31,2021-12-31,2021-09-30,2021-06-30,2021-03-31,2020-12-31,2020-09-30,2020-06-30,2020-03-31,2019-12-31,2019-09-30
Tax Effect Of Unusual Items,NaN,-201040800.0,NaN,NaN,NaN,46571600.0,NaN,NaN,NaN,644000.0,NaN,NaN,NaN,19372200.0,NaN
Tax Rate For Calcs,NaN,0.211,NaN,NaN,NaN,0.173,NaN,NaN,NaN,0.23,NaN,NaN,NaN,0.249,NaN
Normalized EBITDA,NaN,10355600000.0,NaN,NaN,NaN,10374200000.0,NaN,NaN,NaN,7656600000.0,NaN,NaN,NaN,9062200000.0,NaN
Total Unusual Items,NaN,-952800000.0,NaN,NaN,NaN,269200000.0,NaN,NaN,NaN,2800000.0,NaN,NaN,NaN,77800000.0,NaN
Total Unusual Items Excluding Goodwill,NaN,-952800000.0,NaN,NaN,NaN,269200000.0,NaN,NaN,NaN,2800000.0,NaN,NaN,NaN,77800000.0,NaN
Net Income From Continuing Operation Net Minority Interest,NaN,6177400000.0,NaN,NaN,NaN,7545200000.0,NaN,NaN,NaN,4730500000.0,NaN,NaN,NaN,6025400000.0,NaN
Reconciled Depreciation,NaN,370400000.0,NaN,NaN,NaN,329700000.0,NaN,NaN,NaN,300600000.0,NaN,NaN,NaN,1617900000.0,NaN
Reconciled Cost Of Revenue,NaN,9975400000.0,NaN,NaN,NaN,10642700000.0,NaN,NaN,NaN,9455700000.0,NaN,NaN,NaN,9961200000.0,NaN
EBIT,NaN,9032400000.0,NaN,NaN,NaN,10313700000.0,NaN,NaN,NaN,7358800000.0,NaN,NaN,NaN,9140000000.0,NaN
Net Interest Income,NaN,-1163300000.0,NaN,NaN,NaN,-1176600000.0,NaN,NaN,NaN,-1200400000.0,NaN,NaN,NaN,-1085200000.0,NaN
Interest Expense,NaN,1207000000.0,NaN,NaN,NaN,1185800000.0,NaN,NaN,NaN,1218100000.0,NaN,NaN,NaN,1121900000.0,NaN
Interest Income,NaN,43700000.0,NaN,NaN,NaN,9200000.0,NaN,NaN,NaN,17700000.0,NaN,NaN,NaN,36700000.0,NaN
Normalized Income,NaN,6929159200.0,NaN,NaN,NaN,7322571600.0,NaN,NaN,NaN,4728344000.0,NaN,NaN,NaN,5966972200.0,NaN
Net Income From Continuing And Discontinued Operation,NaN,6177400000.0,NaN,NaN,NaN,7545200000.0,NaN,NaN,NaN,4730500000.0,NaN,NaN,NaN,6025400000.0,NaN
Total Expenses,NaN,12838000000.0,NaN,NaN,NaN,13350200000.0,NaN,NaN,NaN,12001300000.0,NaN,NaN,NaN,12190600000.0,NaN
Rent Expense Supplemental,NaN,2349700000.0,NaN,NaN,NaN,2335000000.0,NaN,NaN,NaN,2207500000.0,NaN,NaN,NaN,2200600000.0,NaN
Total Operating Income As Reported,NaN,9371000000.0,NaN,NaN,NaN,10356000000.0,NaN,NaN,NaN,7324000000.0,NaN,NaN,NaN,9069800000.0,NaN
Diluted Average Shares,738275000.0,741300000.0,745125000.0,748400000.0,750950000.0,751800000.0,751675000.0,751100000.0,750175000.0,750100000.0,751175000.0,754600000.0,759675000.0,764900000.0,770300000.0
Basic Average Shares,733575000.0,736500000.0,740150000.0,743200000.0,745500000.0,746300000.0,746175000.0,745550000.0,744850000.0,744600000.0,745575000.0,748600000.0,753075000.0,758100000.0,763125000.0
Diluted EPS,9.3,8.33,7.93,8.12,9.47,10.04,9.7,9.19,6.89,6.31,6.55,6.31,7.63,7.88,7.62
Basic EPS,9.37,8.39,7.99,8.18,9.54,10.11,9.76,9.24,6.92,6.35,6.6,6.36,7.7,7.95,7.69
Diluted NI Availto Com Stockholders,NaN,6177400000.0,NaN,NaN,NaN,7545200000.0,NaN,NaN,NaN,4730500000.0,NaN,NaN,NaN,6025400000.0,NaN
Net Income Common Stockholders,NaN,6177400000.0,NaN,NaN,NaN,7545200000.0,NaN,NaN,NaN,4730500000.0,NaN,NaN,NaN,6025400000.0,NaN
Net Income,NaN,6177400000.0,NaN,NaN,NaN,7545200000.0,NaN,NaN,NaN,4730500000.0,NaN,NaN,NaN,6025400000.0,NaN
Net Income Including Noncontrolling Interests,NaN,6177400000.0,NaN,NaN,NaN,7545200000.0,NaN,NaN,NaN,4730500000.0,NaN,NaN,NaN,6025400000.0,NaN
Net Income Continuous Operations,NaN,6177400000.0,NaN,NaN,NaN,7545200000.0,NaN,NaN,NaN,4730500000.0,NaN,NaN,NaN,6025400000.0,NaN
Tax Provision,NaN,1648000000.0,NaN,NaN,NaN,1582700000.0,NaN,NaN,NaN,1410200000.0,NaN,NaN,NaN,1992700000.0,NaN
Pretax Income,NaN,7825400000.0,NaN,NaN,NaN,9127900000.0,NaN,NaN,NaN,6140700000.0,NaN,NaN,NaN,8018100000.0,NaN
Other Income Expense,NaN,-1355900000.0,NaN,NaN,NaN,431800000.0,NaN,NaN,NaN,134600000.0,NaN,NaN,NaN,217400000.0,NaN
Other Non Operating Income Expenses,NaN,-516300000.0,NaN,NaN,NaN,-14100000.0,NaN,NaN,NaN,14400000.0,NaN,NaN,NaN,-14200000.0,NaN
Special Income Charges,NaN,-1086800000.0,NaN,NaN,NaN,306600000.0,NaN,NaN,NaN,100000.0,NaN,NaN,NaN,30100000.0,NaN
Gain On Sale Of Ppe,NaN,-136800000.0,NaN,NaN,NaN,-75400000.0,NaN,NaN,NaN,-290700000.0,NaN,NaN,NaN,-23100000.0,NaN
Gain On Sale Of Business,NaN,59800000.0,NaN,NaN,NaN,96600000.0,NaN,NaN,NaN,23300000.0,NaN,NaN,NaN,127500000.0,NaN
Write Off,NaN,1009800000.0,NaN,NaN,NaN,-285400000.0,NaN,NaN,NaN,-267500000.0,NaN,NaN,NaN,74300000.0,NaN
Impairment Of Capital Assets,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-267500000.0,NaN,NaN,NaN,74300000.0,NaN
Earnings From Equity Interest,NaN,113200000.0,NaN,NaN,NaN,176700000.0,NaN,NaN,NaN,117400000.0,NaN,NaN,NaN,153800000.0,NaN
Gain On Sale Of Security,NaN,134000000.0,NaN,NaN,NaN,-37400000.0,NaN,NaN,NaN,2700000.0,NaN,NaN,NaN,47700000.0,NaN
Net Non Operating Interest Income Expense,NaN,-1163300000.0,NaN,NaN,NaN,-1176600000.0,NaN,NaN,NaN,-1200400000.0,NaN,NaN,NaN,-1085200000.0,NaN
Interest Expense Non Operating,NaN,1207000000.0,NaN,NaN,NaN,1185800000.0,NaN,NaN,NaN,1218100000.0,NaN,NaN,NaN,1121900000.0,NaN
Interest Income Non Operating,NaN,43700000.0,NaN,NaN,NaN,9200000.0,NaN,NaN,NaN,17700000.0,NaN,NaN,NaN,36700000.0,NaN
Operating Income,NaN,10344600000.0,NaN,NaN,NaN,9872700000.0,NaN,NaN,NaN,7206500000.0,NaN,NaN,NaN,8885900000.0,NaN
Operating Expense,NaN,2862600000.0,NaN,NaN,NaN,2707500000.0,NaN,NaN,NaN,2545600000.0,NaN,NaN,NaN,2229400000.0,NaN
Other Operating Expenses,NaN,973600000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-183900000.0,NaN
Depreciation Amortization Depletion Income Statement,NaN,370400000.0,NaN,NaN,NaN,329700000.0,NaN,NaN,NaN,300600000.0,NaN,NaN,NaN,NaN,NaN
Depreciation And Amortization In Income Statement,NaN,370400000.0,NaN,NaN,NaN,329700000.0,NaN,NaN,NaN,300600000.0,NaN,NaN,NaN,NaN,NaN
Selling General And Administration,NaN,2492200000.0,NaN,NaN,NaN,2377800000.0,NaN,NaN,NaN,2245000000.0,NaN,NaN,NaN,2229400000.0,NaN
Gross Profit,NaN,13207200000.0,NaN,NaN,NaN,12580200000.0,NaN,NaN,NaN,9752100000.0,NaN,NaN,NaN,11115300000.0,NaN
Cost Of Revenue,NaN,9975400000.0,NaN,NaN,NaN,10642700000.0,NaN,NaN,NaN,9455700000.0,NaN,NaN,NaN,9961200000.0,NaN
Total Revenue,NaN,23182600000.0,NaN,NaN,NaN,23222900000.0,NaN,NaN,NaN,19207800000.0,NaN,NaN,NaN,21076500000.0,NaN
Operating Revenue,NaN,22854200000.0,NaN,NaN,NaN,22872800000.0,NaN,NaN,NaN,18865300000.0,NaN,NaN,NaN,21076500000.0,NaN

In [225]:
ticker.quarterly_financials

,2023-06-30,2023-03-31,2022-12-31,2022-09-30,2022-06-30
Tax Effect Of Unusual Items,0.0,0.0,1134600.0,0.0,0.0
Tax Rate For Calcs,0.18,0.205,0.186,0.218674,0.157
Normalized EBITDA,3242100000.0,2696000000.0,2747100000.0,2935700000.0,1792700000.0
Total Unusual Items,8900000.0,-154900000.0,6100000.0,600000.0,-879000000.0
Total Unusual Items Excluding Goodwill,8900000.0,-154900000.0,6100000.0,600000.0,-879000000.0
Net Income From Continuing Operation Net Minority Interest,2310400000.0,1802300000.0,1903400000.0,1981600000.0,1188000000.0
Reconciled Depreciation,95200000.0,99300000.0,91400000.0,93300000.0,93000000.0
Reconciled Cost Of Revenue,2766500000.0,2584200000.0,2517600000.0,2426000000.0,2416300000.0
EBIT,3146900000.0,2596700000.0,2661800000.0,2842400000.0,1699700000.0
Net Interest Income,-330200000.0,-329700000.0,-297200000.0,-306200000.0,-290600000.0
Interest Expense,330200000.0,329700000.0,322900000.0,306200000.0,290600000.0
Interest Income,36900000.0,37900000.0,25700000.0,10800000.0,4600000.0
Normalized Income,2310400000.0,1802300000.0,1898434600.0,1981600000.0,1188000000.0
Net Income From Continuing And Discontinued Operation,2310400000.0,1802300000.0,1903400000.0,1981600000.0,1188000000.0
Total Expenses,3393400000.0,3365400000.0,3329300000.0,3108200000.0,4006600000.0
Rent Expense Supplemental,618200000.0,598300000.0,588100000.0,589000000.0,588600000.0
Total Operating Income As Reported,3104100000.0,2532400000.0,2582700000.0,2763900000.0,1711800000.0
Diluted Average Shares,734300000.0,735500000.0,736200000.0,739500000.0,742000000.0
Basic Average Shares,729600000.0,730900000.0,731100000.0,734900000.0,737500000.0
Diluted EPS,3.15,2.45,2.59,2.68,1.6
Basic EPS,3.17,2.47,2.602762,2.7,1.61
Diluted NI Availto Com Stockholders,2310400000.0,1802300000.0,1903400000.0,1981600000.0,1188000000.0
Net Income Common Stockholders,2310400000.0,1802300000.0,1903400000.0,1981600000.0,1188000000.0
Net Income,2310400000.0,1802300000.0,1903400000.0,1981600000.0,1188000000.0
Net Income Including Noncontrolling Interests,2310400000.0,1802300000.0,1903400000.0,1981600000.0,1188000000.0
Net Income Continuous Operations,2310400000.0,1802300000.0,1903400000.0,1981600000.0,1188000000.0
Tax Provision,506300000.0,464700000.0,435500000.0,554600000.0,221100000.0
Pretax Income,2816700000.0,2267000000.0,2338900000.0,2536200000.0,1409100000.0
Other Income Expense,42800000.0,64300000.0,38900000.0,78500000.0,-12100000.0
Other Non Operating Income Expenses,42800000.0,64300000.0,8100000.0,78500000.0,-12100000.0
Special Income Charges,2300000.0,-167800000.0,-39200000.0,-49800000.0,-906000000.0
Gain On Sale Of Ppe,-5000000.0,-400000.0,-66000000.0,-68100000.0,-32200000.0
Gain On Sale Of Business,25300000.0,13100000.0,26800000.0,18300000.0,8900000.0
Write Off,18000000.0,180500000.0,0.0,0.0,882700000.0
Earnings From Equity Interest,33500000.0,39200000.0,24700000.0,37300000.0,19900000.0
Gain On Sale Of Security,6600000.0,12900000.0,45300000.0,50400000.0,27000000.0
Net Non Operating Interest Income Expense,-330200000.0,-329700000.0,-297200000.0,-306200000.0,-290600000.0
Interest Expense Non Operating,330200000.0,329700000.0,322900000.0,306200000.0,290600000.0
Interest Income Non Operating,36900000.0,37900000.0,25700000.0,10800000.0,4600000.0
Operating Income,3104100000.0,2532400000.0,2597200000.0,2763900000.0,1711800000.0
Operating Expense,626900000.0,781200000.0,811700000.0,682200000.0,1590300000.0
Other Operating Expenses,-35800000.0,128600000.0,14500000.0,12500000.0,886100000.0
Depreciation Amortization Depletion Income Statement,95200000.0,99300000.0,91400000.0,93300000.0,93000000.0
Depreciation And Amortization In Income Statement,95200000.0,99300000.0,91400000.0,93300000.0,93000000.0
Selling General And Administration,567500000.0,553300000.0,720300000.0,576400000.0,611200000.0
General And Administrative Expense,NaN,553300000.0,NaN,NaN,NaN
Other Gand A,NaN,553300000.0,NaN,NaN,NaN
Gross Profit,3731000000.0,3313600000.0,3408900000.0,3446100000.0,3302100000.0
Cost Of Revenue,2766500000.0,2584200000.0,2517600000.0,2426000000.0,2416300000.0
Total Revenue,6497500000.0,5897800000.0,5926500000.0,5872100000.0,5718400000.0
Operating Revenue,6420300000.0,5811800000.0,5853400000.0,5796000000.0,5639600000.0

### Annual and Quarterly Balance Sheet

In [226]:
ticker.balance_sheet

,2022-12-31,2021-12-31,2020-12-31,2019-12-31
Treasury Shares Number,929300000.0,915800000.0,915200000.0,914300000.0
Ordinary Shares Number,731300000.0,744800000.0,745400000.0,746300000.0
Share Issued,1660600000.0,1660600000.0,1660600000.0,1660600000.0
Net Debt,33319700000.0,30913500000.0,31747700000.0,33219600000.0
Total Debt,48037900000.0,48643600000.0,48518100000.0,46875900000.0
...,...,...,...,...
Inventory,52000000.0,55600000.0,51100000.0,50200000.0
Receivables,2115000000.0,1872400000.0,2110300000.0,2224200000.0
Accounts Receivable,2115000000.0,1872400000.0,2110300000.0,2224200000.0
Cash Cash Equivalents And Short Term Investments,2583800000.0,4709200000.0,3449100000.0,898500000.0
Cash And Cash Equivalents,2583800000.0,4709200000.0,3449100000.0,898500000.0

In [227]:
ticker.quarterly_balance_sheet

,2023-06-30,2023-03-31,2022-12-31,2022-09-30,2022-06-30
Treasury Shares Number,931900000.0,930500000.0,929300000.0,928200000.0,924900000.0
Ordinary Shares Number,728763452.0,730093896.0,731300000.0,732423892.0,735717271.0
Share Issued,1660663452.0,1660593896.0,1660600000.0,1660623892.0,1660617271.0
Net Debt,34084500000.0,33419800000.0,33319700000.0,32037900000.0,32704000000.0
Total Debt,48471500000.0,49919200000.0,48037900000.0,47287900000.0,47585500000.0
...,...,...,...,...,...
Inventory,52400000.0,51500000.0,52000000.0,43400000.0,43300000.0
Receivables,2193600000.0,2075500000.0,2115000000.0,1889900000.0,1836700000.0
Accounts Receivable,2193600000.0,2075500000.0,2115000000.0,1889900000.0,1836700000.0
Cash Cash Equivalents And Short Term Investments,1625600000.0,3708100000.0,2583800000.0,2828300000.0,1872500000.0
Cash And Cash Equivalents,1625600000.0,3708100000.0,2583800000.0,2828300000.0,1872500000.0

### Annual and Quarterly Cashflow Statement

In [228]:
ticker.cashflow

,2022-12-31,2021-12-31,2020-12-31,2019-12-31
Free Cash Flow,5487500000.0,7101500000.0,4624400000.0,5728400000.0
Repurchase Of Capital Stock,-3896000000.0,-845500000.0,-907800000.0,-4976200000.0
Repayment Of Debt,-2202400000.0,-2240000000.0,-2411700000.0,-2061900000.0
Issuance Of Debt,3374500000.0,1154400000.0,5543000000.0,4499000000.0
Capital Expenditure,-1899200000.0,-2040000000.0,-1640800000.0,-2393700000.0
Interest Paid Supplemental Data,1183500000.0,1197300000.0,1136000000.0,1066500000.0
Income Tax Paid Supplemental Data,3023500000.0,2403900000.0,1441900000.0,1589700000.0
End Cash Position,2583800000.0,4709200000.0,3449100000.0,898500000.0
Other Cash Adjustment Outside Changein Cash,NaN,NaN,NaN,0.0
Beginning Cash Position,4709200000.0,3449100000.0,898500000.0,866000000.0
Effect Of Exchange Rate Changes,-253800000.0,-120100000.0,80200000.0,-23700000.0
Changes In Cash,-1871600000.0,1380200000.0,2470400000.0,56200000.0
Financing Cash Flow,-6580200000.0,-5595600000.0,-2249000000.0,-4994800000.0
Cash Flow From Continuing Financing Activities,-6580200000.0,-5595600000.0,-2249000000.0,-4994800000.0
Net Other Financing Charges,38200000.0,-46700000.0,-122000000.0,-23500000.0
Proceeds From Stock Option Exercised,286400000.0,239000000.0,173500000.0,327000000.0
Cash Dividends Paid,-4168200000.0,-3918600000.0,-3752900000.0,-3581900000.0
Common Stock Dividend Paid,-4168200000.0,-3918600000.0,-3752900000.0,-3581900000.0
Net Common Stock Issuance,-3896000000.0,-845500000.0,-907800000.0,-4976200000.0
Common Stock Payments,-3896000000.0,-845500000.0,-907800000.0,-4976200000.0
Net Issuance Payments Of Debt,1197600000.0,-1070500000.0,2238200000.0,3236300000.0
Net Short Term Debt Issuance,25500000.0,15100000.0,-893100000.0,799200000.0
Net Long Term Debt Issuance,1172100000.0,-1085600000.0,3131300000.0,2437100000.0
Long Term Debt Payments,-2202400000.0,-2240000000.0,-2411700000.0,-2061900000.0
Long Term Debt Issuance,3374500000.0,1154400000.0,5543000000.0,4499000000.0
Investing Cash Flow,-2678100000.0,-2165700000.0,-1545800000.0,-3071100000.0
Cash Flow From Continuing Investing Activities,-2678100000.0,-2165700000.0,-1545800000.0,-3071100000.0
Net Other Investing Changes,-456700000.0,-53900000.0,57400000.0,-628500000.0
Net Business Purchase And Sale,-322200000.0,-71800000.0,37600000.0,-48900000.0
Sale Of Business,445900000.0,196200000.0,76300000.0,340800000.0
Purchase Of Business,-807000000.0,-374200000.0,-66100000.0,-540900000.0
Net PPE Purchase And Sale,38900000.0,106200000.0,27400000.0,151200000.0
Sale Of PPE,38900000.0,106200000.0,27400000.0,151200000.0
Capital Expenditure Reported,-1899200000.0,-2040000000.0,-1640800000.0,-2393700000.0
Operating Cash Flow,7386700000.0,9141500000.0,6265200000.0,8122100000.0
Cash Flow From Continuing Operating Activities,7386700000.0,9141500000.0,6265200000.0,8122100000.0
Change In Working Capital,-644600000.0,454200000.0,-212100000.0,298500000.0
Change In Payables And Accrued Expense,-386100000.0,206500000.0,-136700000.0,142700000.0
Change In Accrued Expense,129300000.0,284000000.0,44400000.0,-3900000.0
Change In Payable,-515400000.0,-77500000.0,-181100000.0,146600000.0
Change In Account Payable,31300000.0,225000000.0,-137500000.0,-26800000.0
Change In Tax Payable,-546700000.0,-302500000.0,-43600000.0,173400000.0
Change In Income Tax Payable,-546700000.0,-302500000.0,-43600000.0,173400000.0
Change In Inventory,5600000.0,-62200000.0,-68600000.0,128800000.0
Change In Receivables,-264100000.0,309900000.0,-6800000.0,27000000.0
Changes In Account Receivables,-264100000.0,309900000.0,-6800000.0,27000000.0
Other Non Cash Items,1853900000.0,1142100000.0,1746800000.0,1798200000.0
Stock Based Compensation,166700000.0,139200000.0,92400000.0,109600000.0
Deferred Tax,-345700000.0,-428300000.0,6400000.0,149700000.0
Deferred Income Tax,-345700000.0,-428300000.0,6400000.0,149700000.0
Depreciation Amortization Depletion,1870600000.0,1868100000.0,1751400000.0,1617900000.0
Depreciation And Amortization,1870600000.0,1868100000.0,1751400000.0,1617900000.0
Operating Gains Losses,732700000.0,-97800000.0,-28200000.0,-128200000.0
Gain Loss On Sale Of Business,732700000.0,-97800000.0,-28200000.0,-128200000.0
Net Income From Continuing Operations,6177400000.0,7545200000.0,4730500000.0,6025400000.0

In [229]:
ticker.quarterly_cashflow

,2023-06-30,2023-03-31,2022-12-31,2022-09-30,2022-06-30
Free Cash Flow,1146800000.0,1917400000.0,1672500000.0,1902700000.0,180200000.0
Repurchase Of Capital Stock,-569700000.0,-578400000.0,-489100000.0,-869200000.0,-1031200000.0
Repayment Of Debt,-1376900000.0,0.0,-600000.0,-400000.0,-850800000.0
Issuance Of Debt,0.0,1054300000.0,0.0,1500000000.0,1874500000.0
Capital Expenditure,-526500000.0,-503300000.0,-528900000.0,-531200000.0,-437900000.0
End Cash Position,1625600000.0,3708100000.0,2583800000.0,2828300000.0,1872500000.0
Beginning Cash Position,3708100000.0,2583800000.0,2828300000.0,1872500000.0,2335700000.0
Effect Of Exchange Rate Changes,8500000.0,3300000.0,142400000.0,-198600000.0,-75400000.0
Changes In Cash,-2091000000.0,1121000000.0,-386900000.0,1154400000.0,-387800000.0
Financing Cash Flow,-3093800000.0,-558400000.0,-1517000000.0,-546400000.0,-686700000.0
Cash Flow From Continuing Financing Activities,-3093800000.0,-558400000.0,-1517000000.0,-546400000.0,-686700000.0
Net Other Financing Charges,43800000.0,-9700000.0,-10500000.0,80900000.0,-19600000.0
Proceeds From Stock Option Exercised,74900000.0,73800000.0,118100000.0,62400000.0,47200000.0
Cash Dividends Paid,-1108800000.0,-1111200000.0,-1111500000.0,-1014700000.0,-1016900000.0
Common Stock Dividend Paid,-1108800000.0,-1111200000.0,-1111500000.0,-1014700000.0,-1016900000.0
Net Common Stock Issuance,-569700000.0,-578400000.0,-489100000.0,-869200000.0,-1031200000.0
Common Stock Payments,-569700000.0,-578400000.0,-489100000.0,-869200000.0,-1031200000.0
Net Issuance Payments Of Debt,-1534000000.0,1067100000.0,14200000.0,1194200000.0,1333800000.0
Net Short Term Debt Issuance,-157100000.0,12800000.0,14800000.0,-305400000.0,310100000.0
Net Long Term Debt Issuance,-1376900000.0,1054300000.0,-600000.0,1499600000.0,1023700000.0
Long Term Debt Payments,-1376900000.0,0.0,-600000.0,-400000.0,-850800000.0
Long Term Debt Issuance,0.0,1054300000.0,0.0,1500000000.0,1874500000.0
Investing Cash Flow,-670500000.0,-741300000.0,-1071300000.0,-733100000.0,-319200000.0
Cash Flow From Continuing Investing Activities,-670500000.0,-741300000.0,-1071300000.0,-733100000.0,-319200000.0
Net Other Investing Changes,-92900000.0,-179200000.0,-146100000.0,-93800000.0,-128800000.0
Net Business Purchase And Sale,-54800000.0,-76800000.0,-374000000.0,-119200000.0,241200000.0
Sale Of Business,59200000.0,20800000.0,44600000.0,33100000.0,351700000.0
Purchase Of Business,-114000000.0,-97600000.0,-457500000.0,-152300000.0,-110500000.0
Net PPE Purchase And Sale,3700000.0,18000000.0,16600000.0,11100000.0,6300000.0
Sale Of PPE,3700000.0,18000000.0,16600000.0,11100000.0,6300000.0
Capital Expenditure Reported,-526500000.0,-503300000.0,-528900000.0,-531200000.0,-437900000.0
Operating Cash Flow,1673300000.0,2420700000.0,2201400000.0,2433900000.0,618100000.0
Cash Flow From Continuing Operating Activities,1673300000.0,2420700000.0,2201400000.0,2433900000.0,618100000.0
Change In Working Capital,-975600000.0,195100000.0,-140000000.0,190300000.0,-1168300000.0
Other Non Cash Items,-46400000.0,-30800000.0,1593300000.0,-45600000.0,234200000.0
Stock Based Compensation,45200000.0,49700000.0,35800000.0,38300000.0,38300000.0
Deferred Tax,-152500000.0,-86100000.0,37400000.0,-196300000.0,-136300000.0
Deferred Income Tax,-152500000.0,-86100000.0,37400000.0,-196300000.0,-136300000.0
Depreciation Amortization Depletion,492200000.0,490500000.0,463100000.0,465600000.0,462200000.0
Depreciation And Amortization,492200000.0,490500000.0,463100000.0,465600000.0,462200000.0
Net Income From Continuing Operations,2310400000.0,1802300000.0,1903400000.0,1981600000.0,1188000000.0

In [236]:
ticker.earnings_dates

                           EPS Estimate  Reported EPS  Surprise(%)
Earnings Date
2024-07-25 09:00:00-04:00           NaN           NaN          NaN
2024-04-23 09:00:00-04:00           NaN           NaN          NaN
2024-01-29 09:00:00-05:00           NaN           NaN          NaN
2023-10-25 09:00:00-04:00          2.77           NaN          NaN
2023-07-27 03:00:00-04:00          2.79          3.17       0.1378
2023-04-25 03:00:00-04:00          2.33          2.63       0.1280
2023-01-31 02:00:00-05:00          2.45          2.59       0.0552
2022-10-27 03:00:00-04:00          2.58          2.68       0.0400
2022-07-26 03:00:00-04:00          2.47          2.55       0.0327
2022-04-28 03:00:00-04:00          2.17          2.28       0.0514
2022-01-27 02:00:00-05:00          2.34          2.23      -0.0454
2021-10-27 03:00:00-04:00          2.46          2.76       0.1216

In [237]:
ticker.quarterly_cashflow

,2023-06-30,2023-03-31,2022-12-31,2022-09-30,2022-06-30
Free Cash Flow,1146800000.0,1917400000.0,1672500000.0,1902700000.0,180200000.0
Repurchase Of Capital Stock,-569700000.0,-578400000.0,-489100000.0,-869200000.0,-1031200000.0
Repayment Of Debt,-1376900000.0,0.0,-600000.0,-400000.0,-850800000.0
Issuance Of Debt,0.0,1054300000.0,0.0,1500000000.0,1874500000.0
Capital Expenditure,-526500000.0,-503300000.0,-528900000.0,-531200000.0,-437900000.0
End Cash Position,1625600000.0,3708100000.0,2583800000.0,2828300000.0,1872500000.0
Beginning Cash Position,3708100000.0,2583800000.0,2828300000.0,1872500000.0,2335700000.0
Effect Of Exchange Rate Changes,8500000.0,3300000.0,142400000.0,-198600000.0,-75400000.0
Changes In Cash,-2091000000.0,1121000000.0,-386900000.0,1154400000.0,-387800000.0
Financing Cash Flow,-3093800000.0,-558400000.0,-1517000000.0,-546400000.0,-686700000.0
Cash Flow From Continuing Financing Activities,-3093800000.0,-558400000.0,-1517000000.0,-546400000.0,-686700000.0
Net Other Financing Charges,43800000.0,-9700000.0,-10500000.0,80900000.0,-19600000.0
Proceeds From Stock Option Exercised,74900000.0,73800000.0,118100000.0,62400000.0,47200000.0
Cash Dividends Paid,-1108800000.0,-1111200000.0,-1111500000.0,-1014700000.0,-1016900000.0
Common Stock Dividend Paid,-1108800000.0,-1111200000.0,-1111500000.0,-1014700000.0,-1016900000.0
Net Common Stock Issuance,-569700000.0,-578400000.0,-489100000.0,-869200000.0,-1031200000.0
Common Stock Payments,-569700000.0,-578400000.0,-489100000.0,-869200000.0,-1031200000.0
Net Issuance Payments Of Debt,-1534000000.0,1067100000.0,14200000.0,1194200000.0,1333800000.0
Net Short Term Debt Issuance,-157100000.0,12800000.0,14800000.0,-305400000.0,310100000.0
Net Long Term Debt Issuance,-1376900000.0,1054300000.0,-600000.0,1499600000.0,1023700000.0
Long Term Debt Payments,-1376900000.0,0.0,-600000.0,-400000.0,-850800000.0
Long Term Debt Issuance,0.0,1054300000.0,0.0,1500000000.0,1874500000.0
Investing Cash Flow,-670500000.0,-741300000.0,-1071300000.0,-733100000.0,-319200000.0
Cash Flow From Continuing Investing Activities,-670500000.0,-741300000.0,-1071300000.0,-733100000.0,-319200000.0
Net Other Investing Changes,-92900000.0,-179200000.0,-146100000.0,-93800000.0,-128800000.0
Net Business Purchase And Sale,-54800000.0,-76800000.0,-374000000.0,-119200000.0,241200000.0
Sale Of Business,59200000.0,20800000.0,44600000.0,33100000.0,351700000.0
Purchase Of Business,-114000000.0,-97600000.0,-457500000.0,-152300000.0,-110500000.0
Net PPE Purchase And Sale,3700000.0,18000000.0,16600000.0,11100000.0,6300000.0
Sale Of PPE,3700000.0,18000000.0,16600000.0,11100000.0,6300000.0
Capital Expenditure Reported,-526500000.0,-503300000.0,-528900000.0,-531200000.0,-437900000.0
Operating Cash Flow,1673300000.0,2420700000.0,2201400000.0,2433900000.0,618100000.0
Cash Flow From Continuing Operating Activities,1673300000.0,2420700000.0,2201400000.0,2433900000.0,618100000.0
Change In Working Capital,-975600000.0,195100000.0,-140000000.0,190300000.0,-1168300000.0
Other Non Cash Items,-46400000.0,-30800000.0,1593300000.0,-45600000.0,234200000.0
Stock Based Compensation,45200000.0,49700000.0,35800000.0,38300000.0,38300000.0
Deferred Tax,-152500000.0,-86100000.0,37400000.0,-196300000.0,-136300000.0
Deferred Income Tax,-152500000.0,-86100000.0,37400000.0,-196300000.0,-136300000.0
Depreciation Amortization Depletion,492200000.0,490500000.0,463100000.0,465600000.0,462200000.0
Depreciation And Amortization,492200000.0,490500000.0,463100000.0,465600000.0,462200000.0
Net Income From Continuing Operations,2310400000.0,1802300000.0,1903400000.0,1981600000.0,1188000000.0

### Sustainability: Environmental, Social and Governance (ESG)

In [238]:
# ticker.sustainability

### Analyst Recommendations

In [233]:
# ticker.recommendations.info()

YFNotImplementedError: Have not implemented fetching 'recommendations' from Yahoo API

In [ ]:
ticker.recommendations.tail(10)

                                  Firm    To Grade From Grade Action
Date
2020-10-20 12:31:45      Credit Suisse  Outperform              main
2020-10-26 08:50:44            KeyBanc  Overweight              main
2020-10-28 16:47:21          JP Morgan  Overweight              main
2020-10-30 11:53:22      Raymond James  Strong Buy              main
2020-10-30 12:45:43      Credit Suisse  Outperform              main
2020-10-30 12:50:35     Morgan Stanley  Overweight              main
2020-10-30 15:15:15  Canaccord Genuity         Buy              main
2020-10-30 17:03:14             Mizuho         Buy              main
2020-10-30 17:06:53        Wells Fargo  Overweight              main
2020-10-30 17:14:48  Truist Securities         Buy              main

### Upcoming Events

In [ ]:
ticker.calendar

                                    0                    1
Earnings Date     2021-01-27 00:00:00  2021-02-01 00:00:00
Earnings Average                 3.19                 3.19
Earnings Low                     2.67                 2.67
Earnings High                    3.63                 3.63
Revenue Average           26288700000          26288700000
Revenue Low               25412000000          25412000000
Revenue High              26993000000          26993000000

### Option Expiration Dates

In [ ]:
ticker.options

('2020-12-30',
 '2021-01-07',
 '2021-01-14',
 '2021-01-21',
 '2021-01-28',
 '2021-02-04',
 '2021-02-18',
 '2021-03-18',
 '2021-06-17',
 '2021-07-15',
 '2021-09-16',
 '2022-01-20',
 '2022-06-16',
 '2022-09-15',
 '2023-01-19',
 '2026-02-20')

In [ ]:
expiration = ticker.options[0]

In [ ]:
options = ticker.option_chain(expiration)

In [ ]:
options.calls.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45 entries, 0 to 44
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   contractSymbol     45 non-null     object
 1   lastTradeDate      45 non-null     datetime64[ns]
 2   strike             45 non-null     float64
 3   lastPrice          45 non-null     float64
 4   bid                45 non-null     float64
 5   ask                45 non-null     float64
 6   change             45 non-null     float64
 7   percentChange      45 non-null     float64
 8   volume             45 non-null     int64
 9   openInterest       45 non-null     int64
 10  impliedVolatility  45 non-null     float64
 11  inTheMoney         45 non-null     bool
 12  contractSize       45 non-null     object
 13  currency           45 non-null     object
dtypes: bool(1), datetime64[ns](1), float64(7), int64(2), object(3)
memory usage: 4.7+ KB

In [ ]:
options.calls.head()

,contractSymbol,lastTradeDate,strike,lastPrice,bid,ask,change,percentChange,volume,openInterest,impliedVolatility,inTheMoney,contractSize,currency
0,FB201231C00195000,2020-12-30 20:54:40,195.0,77.60,76.35,77.5,-4.200005,-5.134480,1,21,1.773439,True,REGULAR,USD
1,FB201231C00200000,2020-12-30 20:39:19,200.0,72.50,71.35,72.5,-5.250000,-6.752411,7,33,1.648439,True,REGULAR,USD
2,FB201231C00205000,2020-12-30 20:22:11,205.0,68.29,66.35,67.5,-4.870003,-6.656647,11,49,1.531252,True,REGULAR,USD
3,FB201231C00210000,2020-12-29 20:31:41,210.0,68.18,61.35,62.5,0.000000,0.000000,2,43,1.414065,True,REGULAR,USD
4,FB201231C00215000,2020-12-24 15:29:26,215.0,55.50,56.35,57.5,0.000000,0.000000,3,35,1.296879,True,REGULAR,USD

In [ ]:
options.puts.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43 entries, 0 to 42
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   contractSymbol     43 non-null     object
 1   lastTradeDate      43 non-null     datetime64[ns]
 2   strike             43 non-null     float64
 3   lastPrice          43 non-null     float64
 4   bid                43 non-null     float64
 5   ask                43 non-null     float64
 6   change             43 non-null     float64
 7   percentChange      43 non-null     float64
 8   volume             42 non-null     float64
 9   openInterest       43 non-null     int64
 10  impliedVolatility  43 non-null     float64
 11  inTheMoney         43 non-null     bool
 12  contractSize       43 non-null     object
 13  currency           43 non-null     object
dtypes: bool(1), datetime64[ns](1), float64(8), int64(1), object(3)
memory usage: 4.5+ KB

## Data Download with proxy server

You can use a proxy server to avoid having your IP blacklisted as illustrated below (but need an actual PROXY_SERVER).

In [ ]:
PROXY_SERVER = 'PROXY_SERVER'

The following will only work with proper PROXY_SERVER...

In [ ]:
# msft = yf.Ticker("MSFT")

# msft.history(proxy=PROXY_SERVER)
# msft.get_actions(proxy=PROXY_SERVER)
# msft.get_dividends(proxy=PROXY_SERVER)
# msft.get_splits(proxy=PROXY_SERVER)
# msft.get_balance_sheet(proxy=PROXY_SERVER)
# msft.get_cashflow(proxy=PROXY_SERVER)
# msft.option_chain(proxy=PROXY_SERVER)

## Downloading multiple symbols

In [ ]:
tickers = yf.Tickers('msft aapl goog')

In [ ]:
tickers

yfinance.Tickers object <MSFT,AAPL,GOOG>

In [ ]:
pd.Series(tickers.tickers['MSFT'].info)

zip                                                                98052-6399
sector                                                             Technology
fullTimeEmployees                                                      163000
longBusinessSummary         Microsoft Corporation develops, licenses, and ...
city                                                                  Redmond
                                                  ...
impliedSharesOutstanding                                                 None
category                                                                 None
fiveYearAverageReturn                                                    None
regularMarketPrice                                                     225.23
logo_url                              https://logo.clearbit.com/microsoft.com
Length: 123, dtype: object

In [ ]:
tickers.tickers['AAPL'].history(period="1mo")

              Open    High     Low   Close     Volume  Dividends  Stock Splits
Date
2020-11-30  116.97  120.97  116.81  119.05  169410200          0             0
2020-12-01  121.01  123.47  120.01  122.72  128166800          0             0
2020-12-02  122.02  123.37  120.89  123.08   89004200          0             0
2020-12-03  123.52  123.78  122.21  122.94   78967600          0             0
2020-12-04  122.60  122.86  121.52  122.25   78260400          0             0
2020-12-07  122.31  124.57  122.25  123.75   86712000          0             0
2020-12-08  124.37  124.98  123.09  124.38   82225500          0             0
2020-12-09  124.53  125.95  121.00  121.78  115089200          0             0
2020-12-10  120.50  123.87  120.15  123.24   81312200          0             0
2020-12-11  122.43  122.76  120.55  122.41   86939800          0             0
2020-12-14  122.60  123.35  121.54  121.78   79184500          0             0
2020-12-15  124.34  127.90  124.13  127.88  157572300          0             0
2020-12-16  127.41  128.37  126.56  127.81   98208600          0             0
2020-12-17  128.90  129.58  128.04  128.70   94359800          0             0
2020-12-18  128.96  129.10  126.12  126.66  192541500          0             0
2020-12-21  125.02  128.31  123.45  128.23  121251600          0             0
2020-12-22  131.61  134.41  129.65  131.88  168904800          0             0
2020-12-23  132.16  132.43  130.78  130.96   88223700          0             0
2020-12-24  131.32  133.46  131.10  131.97   54930100          0             0
2020-12-28  133.99  137.34  133.51  136.69  124486200          0             0
2020-12-29  138.05  138.79  134.34  134.87  120778200          0             0
2020-12-30  135.58  135.99  133.40  133.72   92882124          0             0

In [ ]:
tickers.history(period='1mo').stack(-1)

[*********************100%***********************]  3 of 3 completed

                       Close  Dividends         High          Low  \
Date
2020-11-30 AAPL   119.050003          0   120.970001   116.809998
           GOOG  1760.739990          0  1788.064941  1755.000000
           MSFT   214.070007          0   214.759995   210.839996
2020-12-01 AAPL   122.720001          0   123.470001   120.010002
           GOOG  1798.099976          0  1824.829956  1769.369995
...                      ...        ...          ...          ...
2020-12-29 GOOG  1758.719971          0  1792.439941  1756.089966
           MSFT   224.149994          0   227.179993   223.580002
2020-12-30 AAPL   133.720001          0   135.990005   133.399994
           GOOG  1739.520020          0  1765.094971  1725.680054
           MSFT   221.679993          0   225.630005   221.470001

                        Open  Stock Splits     Volume
Date
2020-11-30 AAPL   116.970001             0  169410200
           GOOG  1781.183960             0    1823800
           MSFT   214.100006             0   33064800
2020-12-01 AAPL   121.010002             0  128166800
           GOOG  1774.369995             0    1739000
...                      ...           ...        ...
2020-12-29 GOOG  1787.790039             0    1298600
           MSFT   226.309998             0   17348000
2020-12-30 AAPL   135.580002             0   92882124
           GOOG  1762.010010             0    1293285
           MSFT   225.229996             0   19273172

[66 rows x 7 columns]

In [ ]:
data = yf.download("SPY AAPL", start="2020-01-01", end="2020-01-05")

[*********************100%***********************]  2 of 2 completed

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 2 entries, 2020-01-02 to 2020-01-03
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   (Adj Close, AAPL)  2 non-null      float64
 1   (Adj Close, SPY)   2 non-null      float64
 2   (Close, AAPL)      2 non-null      float64
 3   (Close, SPY)       2 non-null      float64
 4   (High, AAPL)       2 non-null      float64
 5   (High, SPY)        2 non-null      float64
 6   (Low, AAPL)        2 non-null      float64
 7   (Low, SPY)         2 non-null      float64
 8   (Open, AAPL)       2 non-null      float64
 9   (Open, SPY)        2 non-null      float64
 10  (Volume, AAPL)     2 non-null      int64
 11  (Volume, SPY)      2 non-null      int64
dtypes: float64(10), int64(2)
memory usage: 208.0 bytes

In [ ]:
data = yf.download(
        tickers = "SPY AAPL MSFT", # list or string

        # use "period" instead of start/end
        # valid periods: 1d,5d,1mo,3mo,6mo,1y,2y,5y,10y,ytd,max
        # (optional, default is '1mo')
        period = "5d",

        # fetch data by interval (including intraday if period < 60 days)
        # valid intervals: 1m,2m,5m,15m,30m,60m,90m,1h,1d,5d,1wk,1mo,3mo
        # (optional, default is '1d')
        interval = "1m",

        # group by ticker (to access via data['SPY'])
        # (optional, default is 'column')
        group_by = 'ticker',

        # adjust all OHLC automatically
        # (optional, default is False)
        auto_adjust = True,

        # download pre/post regular market hours data
        # (optional, default is False)
        prepost = True,

        # use threads for mass downloading? (True/False/Integer)
        # (optional, default is True)
        threads = True,

        # proxy URL scheme use use when downloading?
        # (optional, default is None)
        proxy = None
    )

[*********************100%***********************]  3 of 3 completed

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 4045 entries, 2020-12-23 04:15:00-05:00 to 2020-12-30 17:10:00-05:00
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   (MSFT, Open)    2500 non-null   float64
 1   (MSFT, High)    2500 non-null   float64
 2   (MSFT, Low)     2500 non-null   float64
 3   (MSFT, Close)   2500 non-null   float64
 4   (MSFT, Volume)  2500 non-null   float64
 5   (AAPL, Open)    3843 non-null   float64
 6   (AAPL, High)    3843 non-null   float64
 7   (AAPL, Low)     3843 non-null   float64
 8   (AAPL, Close)   3843 non-null   float64
 9   (AAPL, Volume)  3843 non-null   float64
 10  (SPY, Open)     3358 non-null   float64
 11  (SPY, High)     3358 non-null   float64
 12  (SPY, Low)      3358 non-null   float64
 13  (SPY, Close)    3358 non-null   float64
 14  (SPY, Volume)   3358 non-null   float64
dtypes: float64(15)
memory usage: 505.6 KB

In [ ]:
from pandas_datareader import data as pdr

import yfinance as yf
yf.pdr_override()

# download dataframe
data = pdr.get_data_yahoo('SPY',
                          start='2017-01-01',
                          end='2019-04-30',
                          auto_adjust=False)

[*********************100%***********************]  1 of 1 completed

In [ ]:
# auto_adjust = True
data.tail()

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2019-04-23,290.679993,293.140015,290.420013,292.880005,283.410553,52246600
2019-04-24,292.790009,293.160004,292.070007,292.230011,282.781616,50392900
2019-04-25,292.119995,292.779999,290.730011,292.049988,282.607452,57770900
2019-04-26,292.100006,293.489990,291.239990,293.410004,283.923462,50916400
2019-04-29,293.510010,294.450012,293.410004,293.869995,284.368561,57197700

In [ ]:
# auto_adjust = False
data.tail()

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2019-04-23,290.679993,293.140015,290.420013,292.880005,283.410553,52246600
2019-04-24,292.790009,293.160004,292.070007,292.230011,282.781616,50392900
2019-04-25,292.119995,292.779999,290.730011,292.049988,282.607452,57770900
2019-04-26,292.100006,293.489990,291.239990,293.410004,283.923462,50916400
2019-04-29,293.510010,294.450012,293.410004,293.869995,284.368561,57197700